package neuralnet

// A Serializer can be encoded and decoded
// to and from binary data.
//
// Decoding is done by looking SerializerType
// in the Deserializers map to find a
// Deserializer capable of generating this
// kind of Serializer.
type Serializer interface {
	Serialize() []byte
	SerializerType() string
}

// A Deserializer turns binary data into a
// Serializer, given that the binary data
// was generated by the correct type of
// Serializer for this Deserializer.
type Deserializer func(data []byte) (Serializer, error)

// Deserializers maps every registered
// serializer type to its corresponding
// Deserializer.
//
// External packages may set keys in this
// during their init() routines.
var Deserializers = map[string]Deserializer{
	"sigmoid": func(d []byte) (Serializer, error) {
		return Sigmoid{}, nil
	},
}
